pipeline {
    agent any

    tools {
        python 'Python3'
    }

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/Yohannesabesheger/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                cd messaging_app
                python3 -m venv $VENV
                . $VENV/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                cd messaging_app
                . $VENV/bin/activate
                pytest --junitxml=report.xml
                '''
            }
        }

        stage('Archive Test Results') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -rf venv'
        }
    }
}
